//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikipediaWalkerWinFormsDevExpressApp {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WikipediaWalkerWinFormsDevExpressApp.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %C3%81ed%C3%A1n_mac_Gabr%C3%A1in	Bede
        ///%C3%81ed%C3%A1n_mac_Gabr%C3%A1in	Columba
        ///%C3%81ed%C3%A1n_mac_Gabr%C3%A1in	D%C3%A1l_Riata
        ///%C3%81ed%C3%A1n_mac_Gabr%C3%A1in	Great_Britain
        ///%C3%81ed%C3%A1n_mac_Gabr%C3%A1in	Ireland
        ///%C3%81ed%C3%A1n_mac_Gabr%C3%A1in	Isle_of_Man
        ///%C3%81ed%C3%A1n_mac_Gabr%C3%A1in	Monarchy
        ///%C3%81ed%C3%A1n_mac_Gabr%C3%A1in	Orkney
        ///%C3%81ed%C3%A1n_mac_Gabr%C3%A1in	Picts
        ///%C3%81ed%C3%A1n_mac_Gabr%C3%A1in	Scotland
        ///%C3%81ed%C3%A1n_mac_Gabr%C3%A1in	Wales
        ///%C3%85land	20th_century
        ///%C3%85land	Baltic_Sea
        ///%C3% [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string links {
            get {
                return ResourceManager.GetString("links", resourceCulture);
            }
        }
    }
}
